/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        primary: "#6b38d4",
        "primary-container": "#8455ef",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#5516be",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#d0bcff",
        "inverse-primary": "#d0bcff",
        secondary: "#006c49",
        "secondary-container": "#6cf8bb",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00714d",
        background: "#f8f9ff",
        surface: "#f8f9ff",
        "surface-dim": "#d0dbed",
        "surface-bright": "#f8f9ff",
        "surface-container": "#e6eeff",
        "surface-container-low": "#eff4ff",
        "surface-container-high": "#dee9fc",
        "surface-container-highest": "#d9e3f6",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d9e3f6",
        "on-surface": "#121c2a",
        "on-surface-variant": "#494454",
        "outline-variant": "#cbc3d7",
        outline: "#7b7486",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        // Dark mode overrides (applied via .dark)
        dark: {
          surface: "#1a1c2e",
          "surface-dim": "#121422",
          "surface-bright": "#2a2d42",
          "surface-container": "#1e2034",
          "surface-container-low": "#16182a",
          "surface-container-high": "#26283e",
          "on-surface": "#e6e1ec",
          "on-surface-variant": "#cac4d0",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        "label-sm": ["Inter", "system-ui", "sans-serif"],
        "display-lg": ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "label-xs": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-lg": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-xs": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
